Use Elasticsearch 7.10.2
kuzzleio/kuzzle-containers pull request #59
Opened 2021-02-10 10:22 UTC by Yoann-Abbes

## What does this PR do ?

Pull Elasticsearch 7.10.2 officiel docker image to officialy support it in Kuzze
https://github.com/kuzzleio/kuzzle/issues/1966

2021-02-10 14:26 UTC, alexandrebouthinon requested changes

2021-02-10 14:26 UTC, alexandrebouthinon commented on elasticsearch/Dockerfile
> +FROM docker.elastic.co/elasticsearch/elasticsearch:7.10.2
```suggestion
FROM docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
```

2021-05-07 08:42 UTC, alexandrebouthinon approved these changes

2021-05-19 15:49 UTC, Shiranuit commented
Updated to use ES-7.12.1

2021-06-08 12:46 UTC, Aschen commented on elasticsearch/Dockerfile
> +FROM docker.elastic.co/elasticsearch/elasticsearch:7.10.2
We should continue to use `docker.elastic.co/elasticsearch/elasticsearch` because it also contains xpack which has been open sourced under Elastic Licence 
https://discuss.elastic.co/t/what-is-the-difference-between-elasticsearch-oss-and-elasticsearch-images/145372

2021-06-08 12:47 UTC, Aschen approved these changes
We should use https://www.docker.elastic.co/r/elasticsearch/elasticsearch:7.13.1

2021-06-08 13:48 UTC, Shiranuit commented
Moved to ES 7.13.1

2021-06-22 07:55 UTC, merged